openapi: 3.0.0
info:
  title: Health Management API
  version: v1
  description: 健康管理に関するAPIです。
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080/api/v1 # APIのベースURL
paths:
  /users:
    get:
      summary: ユーザーの一覧を取得します。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                    email:
                      type: string
                      format: email
    post:
      summary: 新しいユーザーを作成します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
      responses:
        "201":
          description: 作成成功
        "400":
          description: 無効なリクエスト
  /health-data:
    post:
      summary: 健康データを登録します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  format: int64
                timestamp:
                  type: string
                  format: date-time
                heartRate:
                  type: integer
                steps:
                  type: integer
      responses:
        "201":
          description: 登録成功
        "400":
          description: 無効なリクエスト
